# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BDvFsIckDIXUBVzXezrrqkM1H1rAgWi5
"""

class Array2D():
info=Array2D(3,4):
info.set_item(1,3,persona("jose")):
info.set_item(2,2,persona("diana")):
print(info.get_row_size()):
print(ifo.get_col_size()):
print(info.gey_item(2,2))